name: Deploy Service Container to GHCR
on:
  push
jobs:
  publish-container:
    runs-on: ubuntu-latest
    services:
      postgres-14:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - run: docker container list
      - run: sleep 5
      - run: createdb -U postgres -h localhost -p 5432 prac
      - run: psql -U postgres -h localhost -p 5432 -c "\l"
