name: Deploy Service Container to GHCR
on:
  push
jobs:
  publish-container:
    runs-on: ubuntu-latest
    services:
      postgres-14:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - run: docker container list
      - name: wait for postgres to be ready
        run: |
          while ! pg_isready -U postgres -h localhost -p 5432; do
            echo waiting for db
            sleep 0.1
          done
      - run: createdb -U postgres -h localhost -p 5432 prac
      - run: psql -U postgres -h localhost -p 5432 -c "\l"
