name: Deploy Service Container to GHCR
on:
  push
jobs:
  publish-container:
    runs-on: ubuntu-latest
    services:
      postgres-14:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          PGDATA: /var/lib/postgresql-static/data # bypass data volume
        options: --cidfile /tmp/cidfile --health-cmd "pg_isready -U postgres" --health-interval 0.1s
    steps:
      - run: docker container list
      - run: createdb -U postgres -h localhost -p 5432 prac
      - run: psql -U postgres -h localhost -p 5432 -c "\l"
      - run: docker commit $(cat /tmp/cidfile) ghcr.io/segevmalool/psql-prac:latest
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push ghcr.io/segevmalool/psql-prac:latest
