name: Segev's first github actions
on: [push]
jobs:
  check-out-aws-oidc-integration:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "running on ${{ runner }}"
      - run: echo "token url ${{ ACTIONS_ID_TOKEN_REQUEST_URL }}"
      - run: ls
      - run: pwd
      - run: env
